---

- tags:
    - setup-all
    - setup-nginx-proxy
    - install-all
    - install-nginx-proxy
  block:
    - when: matrix_mautrix_hangouts_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/inject_into_nginx_proxy.yml"

- tags:
    - setup-all
    - setup-mautrix-hangouts
    - install-all
    - install-mautrix-hangouts
  block:
    - when: matrix_mautrix_hangouts_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - when: matrix_mautrix_hangouts_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/setup_install.yml"

- tags:
    - setup-all
    - setup-mautrix-hangouts
  block:
    - when: not matrix_mautrix_hangouts_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/setup_uninstall.yml"
