---

- ansible.builtin.include_tasks: "{{ role_path }}/tasks/setup_redhat7.yml"
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version | int < 8

# RedHat > 7 and Fedora
- ansible.builtin.include_tasks: "{{ role_path }}/tasks/setup_redhat.yml"
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version | int >= 8

- ansible.builtin.include_tasks: "{{ role_path }}/tasks/setup_debian.yml"
  when: ansible_os_family == 'Debian'

- ansible.builtin.include_tasks: "{{ role_path }}/tasks/setup_archlinux.yml"
  when: ansible_distribution == 'Archlinux'
