galaxy_info:
  author: Slavi Pantaleev
  company: Devture Ltd
  description: systemd Docker helper role
  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: Archlinux
      versions:
        - all
    - name: EL
      versions:
        - all
  license: GPL-3.0-or-later
  min_ansible_version: '2.1'
