---

- name: Ensure prometheus-postgres-exporter image is pulled
  community.docker.docker_image:
    name: "{{ prometheus_postgres_exporter_docker_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ prometheus_postgres_exporter_docker_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else prometheus_postgres_exporter_docker_image_force_pull }}"
  register: result
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: result is not failed

- name: Ensure prometheus-postgres-exporter path exist
  ansible.builtin.file:
    path: "{{ prometheus_postgres_exporter_base_path }}"
    state: directory
    mode: 0700
    owner: "{{ prometheus_postgres_exporter_uid }}"
    group: "{{ prometheus_postgres_exporter_gid }}"

- when: prometheus_postgres_exporter_basicauth_enabled | bool
  block:
    # We do this locally, so that we won't need passlib to be installed on the server.
    - name: Generate basic auth file locally
      community.general.htpasswd:
        path: "{{ prometheus_postgres_exporter_basicauth_file_tmp }}"
        name: "{{ prometheus_postgres_exporter_basicauth_user }}"
        password: "{{ prometheus_postgres_exporter_basicauth_password }}"
      become: false
      delegate_to: 127.0.0.1

    - name: Load basic auth file contents
      ansible.builtin.slurp:
        src: "{{ prometheus_postgres_exporter_basicauth_file_tmp }}"
      become: false
      delegate_to: 127.0.0.1
      register: prometheus_postgres_exporter_basicauth_file_contents_raw

    - name: Load basic auth file contents
      ansible.builtin.set_fact:
        prometheus_postgres_exporter_basicauth_file_contents: "{{ prometheus_postgres_exporter_basicauth_file_contents_raw ['content'] | b64decode }}"

    - name: Ensure basic auth file is saved on the server
      ansible.builtin.copy:
        content: "{{ prometheus_postgres_exporter_basicauth_file_contents }}"
        dest: "{{ prometheus_postgres_exporter_basicauth_file }}"
        owner: "{{ prometheus_postgres_exporter_uid }}"
        group: "{{ prometheus_postgres_exporter_gid }}"
        mode: 0640

    - name: Ensure local temporary basic auth file is removed
      ansible.builtin.file:
        path: "{{ prometheus_postgres_exporter_basicauth_file_tmp }}"
        state: absent
      become: false
      delegate_to: 127.0.0.1

    - name: Print basic auth credentials
      debug:
        msg: "login={{ prometheus_postgres_exporter_basicauth_user }} password={{ prometheus_postgres_exporter_basicauth_password }}"
      when: prometheus_postgres_exporter_basicauth_print | bool

- name: Ensure prometheus-postgres-exporter support files are created
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ item }}.j2"
    dest: "{{ prometheus_postgres_exporter_base_path }}/{{ item }}"
    owner: "{{ prometheus_postgres_exporter_uid }}"
    group: "{{ prometheus_postgres_exporter_gid }}"
    mode: 0640
  with_items:
    - env
    - labels

- name: Ensure prometheus-postgres-exporter container network is created
  community.general.docker_network:
    name: "{{ prometheus_postgres_exporter_container_network }}"
    driver: bridge

- name: Ensure prometheus-postgres-exporter systemd service installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/prometheus-postgres-exporter.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ prometheus_postgres_exporter_identifier }}.service"
    mode: 0644
