---

- name: Check existence of Traefik systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ devture_traefik_identifier }}.service"
  register: devture_traefik_service_stat

- when: devture_traefik_service_stat.stat.exists | bool
  block:
    - name: Ensure Traefik systemd service is stopped
      ansible.builtin.systemd:
        name: "{{ devture_traefik_identifier }}"
        state: stopped
        daemon_reload: true

    - name: Ensure Traefik systemd service doesn't exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ devture_traefik_identifier }}.service"
        state: absent

    - name: Remove Traefik directory is removed
      ansible.builtin.file:
        path: "{{ devture_traefik_base_path }}"
        state: absent
