---

- name: Check existence of matrix-heisenbridge service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/matrix-heisenbridge.service"
  register: matrix_heisenbridge_service_stat

- when: matrix_heisenbridge_service_stat.stat.exists | bool
  block:
    - name: Ensure matrix-heisenbridge is stopped
      ansible.builtin.service:
        name: matrix-heisenbridge
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure matrix-heisenbridge.service doesn't exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/matrix-heisenbridge.service"
        state: absent
