---

- name: Fail if matrix-nginx-proxy role already executed
  ansible.builtin.fail:
    msg: >-
      Trying to append Mautrix Facebook's reverse-proxying configuration to matrix-nginx-proxy,
      but it's pointless since the matrix-nginx-proxy role had already executed.
      To fix this, please change the order of roles in your playbook,
      so that the matrix-nginx-proxy role would run after the matrix-bridge-mautrix-facebook role.
  when: matrix_nginx_proxy_role_executed | default(False) | bool

- name: Generate Mautrix Facebook proxying configuration for matrix-nginx-proxy
  ansible.builtin.set_fact:
    matrix_mautrix_facebook_matrix_nginx_proxy_configuration: |
      location {{ matrix_mautrix_facebook_public_endpoint }} {
      {% if matrix_nginx_proxy_enabled | default(False) %}
          {# Use the embedded DNS resolver in Docker containers to discover the service #}
          resolver 127.0.0.11 valid=5s;
          set $backend "matrix-mautrix-facebook:29319";
          proxy_pass http://$backend;
      {% else %}
          {# Generic configuration for use outside of our container setup #}
          proxy_pass http://127.0.0.1:9008;
      {% endif %}
      }

- name: Register Mautrix Facebook proxying configuration with matrix-nginx-proxy
  ansible.builtin.set_fact:
    matrix_nginx_proxy_proxy_matrix_additional_server_configuration_blocks: |
      {{
        matrix_nginx_proxy_proxy_matrix_additional_server_configuration_blocks | default([])
        +
        [matrix_mautrix_facebook_matrix_nginx_proxy_configuration]
      }}

- name: Warn about reverse-proxying if matrix-nginx-proxy not used
  ansible.builtin.debug:
    msg: >-
      NOTE: You've enabled the Mautrix Facebook bridge but are not using the matrix-nginx-proxy
      reverse proxy.
      Please make sure that you're proxying the `{{ matrix_mautrix_facebook_public_endpoint }}`
      URL endpoint to the matrix-mautrix-facebook container.
      You can expose the container's port using the `matrix_mautrix_facebook_container_http_host_bind_port` variable.
  when: "not matrix_nginx_proxy_enabled | default(False) | bool"

- when: matrix_mautrix_facebook_metrics_proxying_enabled | bool
  block:
    - name: Generate mautrix-facebook metrics proxying configuration for matrix-nginx-proxy (matrix.DOMAIN/metrics/mautrix-facebook)
      ansible.builtin.set_fact:
        matrix_mautrix_facebook_nginx_metrics_configuration_block: |
          location /metrics/mautrix-facebook {
            {% if matrix_nginx_proxy_enabled | default(False) %}
              {# Use the embedded DNS resolver in Docker containers to discover the service #}
              resolver 127.0.0.11 valid=5s;
              set $backend "matrix-mautrix-facebook:8000";
              proxy_pass http://$backend/metrics;
            {% else %}
              return 404 "matrix-nginx-proxy is disabled and no host port was bound to the container, so metrics are unavailable";
            {% endif %}
          }

    - name: Register mautrix-facebook metrics proxying configuration with matrix-nginx-proxy (matrix.DOMAIN/metrics/mautrix-facebook)
      ansible.builtin.set_fact:
        matrix_nginx_proxy_proxy_matrix_metrics_additional_system_location_configuration_blocks: |
          {{
            matrix_nginx_proxy_proxy_matrix_metrics_additional_system_location_configuration_blocks | default([])
            +
            [matrix_mautrix_facebook_nginx_metrics_configuration_block]
          }}
