---

devture_timesync_installation_enabled: true

devture_timesync_ntpd_package: "{{ 'systemd-timesyncd' if (ansible_os_family == 'RedHat' and ansible_distribution_major_version | int > 7 and not ansible_distribution == 'Fedora') or (ansible_distribution == 'Ubuntu' and ansible_distribution_major_version | int > 18) else ('systemd' if ansible_os_family in ['Suse', 'Archlinux'] or ansible_distribution == 'Fedora' else 'ntp') }}"
devture_timesync_ntpd_service: "{{ 'systemd-timesyncd' if (ansible_os_family == 'RedHat' and ansible_distribution_major_version | int > 7) or (ansible_distribution == 'Ubuntu' and ansible_distribution_major_version | int > 18) or (ansible_os_family in ['Suse', 'Archlinux']) else ('ntpd' if ansible_os_family == 'RedHat' else 'ntp') }}"
