---

devture_systemd_docker_base_systemd_path: "/etc/systemd/system"

# Specifies the path to use for the `HOME` environment variable for systemd unit files.
# Docker 20.10 complains with `WARNING: Error loading config file: .dockercfg: $HOME is not defined`
# if `$HOME` is not defined, so we define something to make it happy.
devture_systemd_docker_base_systemd_unit_home_path: /root

devture_systemd_docker_base_host_command_docker: "/usr/bin/env docker"
devture_systemd_docker_base_host_command_sh: "/usr/bin/env sh"
devture_systemd_docker_base_host_command_systemctl: "/usr/bin/env systemctl"

# Specifies how various roles will interact with the container system when it comes to pulling images, creating networks, etc.
# Valid options: ansible-module, command
devture_systemd_docker_base_container_system_interaction_method: ansible-module

# Specifies how various roles will pull the image.
# Valid options: ansible-module, command
devture_systemd_docker_base_container_image_pull_method: "{{ devture_systemd_docker_base_container_system_interaction_method }}"

# Specifies how various roles will create container networks.
# Valid options: ansible-module, command
devture_systemd_docker_base_container_network_creation_method: "{{ devture_systemd_docker_base_container_system_interaction_method }}"

# Specifies how long to give to the container stopping process (docker stop --time=X CONTAINER) to run gracefully, before killing the container.
# We use a relatively short interval here, because:
# - certain services ignore SIGTERM and we don't wish to be stuck waiting for long
# - certain services (HTTP servers) may wish to wait for long-polling connections to end and they may not be ending as quickly as we wish
# A few seconds of grace time should be enough for everyone.
devture_systemd_docker_base_container_stop_grace_time_seconds: 3
