---

- name: Fail if required mautrix-googlechat settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item.name }}`).
  when: "item.when | bool and vars[item.name] == ''"
  with_items:
    - {'name': 'matrix_mautrix_googlechat_public_endpoint', when: true}
    - {'name': 'matrix_mautrix_googlechat_appservice_token', when: true}
    - {'name': 'matrix_mautrix_googlechat_homeserver_token', when: true}
    - {'name': 'matrix_mautrix_googlechat_database_hostname', when: "{{ matrix_mautrix_googlechat_database_engine == 'postgres' }}"}
