---

- tags:
    - setup-all
    - setup-rageshake
    - install-all
    - install-rageshake
  block:
    - when: matrix_rageshake_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - when: matrix_rageshake_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- tags:
    - setup-all
    - setup-rageshake
  block:
    - when: not matrix_rageshake_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
