---

# Ansible outputs the message in the `item=` field.
# It's unnecessary to output it again in the actual message, so we don't.
- ansible.builtin.debug:
    msg: ""
  with_items: "{{ devture_playbook_runtime_messages_list }}"
