---

- name: Fail if matrix-nginx-proxy role already executed
  ansible.builtin.fail:
    msg: >-
      Trying to append mautrix-whatapp-metrics's reverse-proxying configuration to matrix-nginx-proxy,
      but it's pointless since the matrix-nginx-proxy role had already executed.
      To fix this, please change the order of roles in your playbook,
      so that the matrix-nginx-proxy role would run after the matrix-bridge-mautrix-instagram role.
  when: matrix_nginx_proxy_role_executed | default(False) | bool

- when: matrix_mautrix_instagram_metrics_proxying_enabled | bool
  block:
    - name: Generate mautrix-instagram metrics proxying configuration for matrix-nginx-proxy (matrix.DOMAIN/metrics/mautrix-instagram)
      ansible.builtin.set_fact:
        matrix_mautrix_instagram_nginx_metrics_configuration_block: |
          location /metrics/mautrix-instagram {
            {% if matrix_nginx_proxy_enabled | default(False) %}
              {# Use the embedded DNS resolver in Docker containers to discover the service #}
              resolver 127.0.0.11 valid=5s;
              set $backend "matrix-mautrix-instagram:8000";
              proxy_pass http://$backend/metrics;
            {% else %}
              return 404 "matrix-nginx-proxy is disabled and no host port was bound to the container, so metrics are unavailable";
            {% endif %}
          }

    - name: Register mautrix-instagram metrics proxying configuration with matrix-nginx-proxy (matrix.DOMAIN/metrics/mautrix-instagram)
      ansible.builtin.set_fact:
        matrix_nginx_proxy_proxy_matrix_metrics_additional_system_location_configuration_blocks: |
          {{
            matrix_nginx_proxy_proxy_matrix_metrics_additional_system_location_configuration_blocks | default([])
            +
            [matrix_mautrix_instagram_nginx_metrics_configuration_block]
          }}
