---
- name: Fail if required mautrix-instagram settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item.name }}`).
  when: "item.when | bool and vars[item.name] == ''"
  with_items:
    - {'name': 'matrix_mautrix_instagram_appservice_token', when: true}
    - {'name': 'matrix_mautrix_instagram_homeserver_token', when: true}
    - {'name': 'matrix_mautrix_instagram_database_hostname', when: "{{ matrix_mautrix_instagram_database_engine == 'postgres' }}"}
