---

- name: Fail if required playbook-state-preserver vars.yml-preservation settings not defined
  fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`) for using vars.yml-preservation.
  when: "vars[item] == ''"
  with_items:
    - devture_playbook_state_preserver_vars_preservation_dst

- name: Preserve vars.yml on the server for easily restoring if it gets lost later on
  ansible.builtin.copy:
    src: "{{ devture_playbook_state_preserver_vars_preservation_src }}"
    dest: "{{ devture_playbook_state_preserver_vars_preservation_dst }}"
    owner: "{{ devture_playbook_state_preserver_uid }}"
    group: "{{ devture_playbook_state_preserver_gid }}"
    mode: "{{ devture_playbook_state_preserver_mode }}"
