---

- name: Save current git-repo status on the target to aid with restoring in case of problems
  block:
    - name: Fail if required playbook-state-preserver commit-hash-preservation settings not defined
      fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`) for using vars.yml-preservation.
      when: "vars[item] == ''"
      with_items:
        - devture_playbook_state_preserver_commit_hash_preservation_dst

    - name: Get local git hash  # noqa command-instead-of-module
      delegate_to: 127.0.0.1
      become: false
      register: git_describe
      changed_when: false
      ansible.builtin.shell:
        git describe
            --always
            --tags
            --dirty
            --long
            --all

    - ansible.builtin.set_fact:
        git_hash: "{{ git_describe.stdout }}"

    - name: Git hash
      ansible.builtin.debug:
        msg: "Git hash: {{ git_hash }}"

    - name: Save git_hash.yml on target
      ansible.builtin.copy:
        content: "{{ git_hash }}"
        dest: "{{ devture_playbook_state_preserver_commit_hash_preservation_dst }}"
        owner: "{{ devture_playbook_state_preserver_uid }}"
        group: "{{ devture_playbook_state_preserver_gid }}"
        mode: "{{ devture_playbook_state_preserver_mode }}"

  rescue:
    - name: Inject git not found warning
      ansible.builtin.set_fact:
        devture_playbook_runtime_messages_list: |
          {{
            devture_playbook_runtime_messages_list | default([])
            +
            [
              "Couldn't find git on the local machine. Continuing without saving the playbook commit hash to the server. You can disable saving the commit hash by setting 'devture_playbook_state_preserver_commit_hash_preservation_enabled: false' in vars.yml"
            ]
          }}
      when: "git_describe.stderr.find('git: not found') != -1"

    - name: Get GIT hash error
      ansible.builtin.fail:
        msg: >-
          Error when trying to get the git hash. Please consult the error message above.
          You can disable saving the commit hash by setting 'devture_playbook_state_preserver_commit_hash_preservation_enabled: false' in vars.yml
      when: "git_describe.stderr.find('git: not found') == -1"
