---

- name: Fail if required Grafana settings not defined
  ansible.builtin.fail:
    msg: >
      You need to define a required configuration setting (`{{ item }}`).
  when: "vars[item] == ''"
  with_items:
    - grafana_identifier
    - grafana_uid
    - grafana_gid
    - grafana_hostname
    - grafana_path_prefix
    - grafana_container_network

- when: grafana_container_labels_traefik_enabled | bool
  block:
    - name: Fail if required Grafana Traefik settings not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`).
      when: "vars[item] == ''"
      with_items:
        - grafana_container_labels_traefik_hostname
        - grafana_container_labels_traefik_path_prefix

    # We ensure it doesn't end with a slash, because we handle both (slash and no-slash).
    # Knowing that `grafana_container_labels_traefik_path_prefix` does not end with a slash
    # ensures we know how to set these routes up without having to do "does it end with a slash" checks elsewhere.
    - name: Fail if grafana_container_labels_traefik_path_prefix ends with a slash
      ansible.builtin.fail:
        msg: >-
          grafana_container_labels_traefik_path_prefix (`{{ grafana_container_labels_traefik_path_prefix }}`) must either be `/` or not end with a slash (e.g. `/grafana`).
      when: "grafana_container_labels_traefik_path_prefix != '/' and grafana_container_labels_traefik_path_prefix[-1] == '/'"
