---

- name: Check existence of Etherpad systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ etherpad_identifier }}.service"
  register: etherpad_service_stat

- when: etherpad_service_stat.stat.exists | bool
  block:
    - name: Ensure Etherpad systemd service is stopped
      ansible.builtin.service:
        name: "{{ etherpad_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure Etherpad systemd service doesn't exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ etherpad_identifier }}.service"
        state: absent

    - name: Ensure Etherpad base directory doesn't exist
      ansible.builtin.file:
        path: "{{ etherpad_base_path }}"
        state: absent
