---
- name: Fail if required matrix-sliding-sync settings not defined
  ansible.builtin.fail:
    msg: >
      You need to define a required configuration setting (`{{ item.name }}`).
  when: "vars[item] == ''"
  with_items:
    - matrix_sliding_sync_hostname
    - matrix_sliding_sync_path_prefix
    - matrix_sliding_sync_database_hostname
    - matrix_sliding_sync_environment_variable_syncv3_secret
