---

- name: Ensure container-socket-proxy path exists
  ansible.builtin.file:
    path: "{{ devture_container_socket_proxy_base_path }}"
    state: directory
    mode: "0750"
    owner: "{{ devture_container_socket_proxy_uid }}"
    group: "{{ devture_container_socket_proxy_gid }}"

- name: Ensure container-socket-proxy support files installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ item }}.j2"
    dest: "{{ devture_container_socket_proxy_base_path }}/{{ item }}"
    owner: "{{ devture_container_socket_proxy_uid }}"
    group: "{{ devture_container_socket_proxy_gid }}"
    mode: 0640
  with_items:
    - env
    - labels

- name: Ensure container-socket-proxy container image is pulled via community.docker.docker_image
  when: devture_systemd_docker_base_container_image_pull_method == 'ansible-module'
  community.docker.docker_image:
    name: "{{ devture_container_socket_proxy_container_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ devture_container_socket_proxy_container_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else devture_container_socket_proxy_container_image_force_pull }}"
  register: result
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: result is not failed

- name: Ensure container-socket-proxy container image is pulled via command
  when: devture_systemd_docker_base_container_image_pull_method == 'command'
  ansible.builtin.command:
    cmd: "{{ devture_systemd_docker_base_host_command_docker }} pull {{ devture_container_socket_proxy_container_image }}"
  register: result
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: result is not failed

- name: Ensure container-socket-proxy container network exists via community.docker.docker_network
  when: devture_systemd_docker_base_container_network_creation_method == 'ansible-module'
  community.docker.docker_network:
    name: "{{ devture_container_socket_proxy_container_network }}"
  until: result is not failed

- name: Ensure container-socket-proxy container network exists via command
  when: devture_systemd_docker_base_container_network_creation_method == 'command'
  ansible.builtin.command:
    cmd: "{{ devture_systemd_docker_base_host_command_docker }} network create {{ devture_container_socket_proxy_container_network }}"
  register: network_creation_result
  failed_when: network_creation_result.rc != 0 and 'already exists' not in network_creation_result.stderr

- name: Ensure container-socket-proxy systemd service installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/devture-container-socket-proxy.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ devture_container_socket_proxy_identifier }}.service"
    mode: 0644
