---

- name: Check existence of container-socket-proxy systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ devture_container_socket_proxy_identifier }}.service"
  register: devture_container_socket_proxy_service_stat

- when: devture_container_socket_proxy_service_stat.stat.exists | bool
  block:
    - name: Ensure container-socket-proxy systemd service is stopped
      ansible.builtin.systemd:
        name: "{{ devture_container_socket_proxy_identifier }}"
        state: stopped
        daemon_reload: true

    - name: Ensure container-socket-proxy systemd service doesn't exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ devture_container_socket_proxy_identifier }}.service"
        state: absent

    - name: Remove container-socket-proxy directory is removed
      ansible.builtin.file:
        path: "{{ devture_container_socket_proxy_base_path }}"
        state: absent
