---

- name: Ensure jitsi-jicofo path exists
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: "0777"
    owner: "{{ jitsi_uid }}"
    group: "{{ jitsi_gid }}"
  with_items:
    - {path: "{{ jitsi_jicofo_base_path }}", when: true}
    - {path: "{{ jitsi_jicofo_config_path }}", when: true}
  when: item.when | bool

- name: Ensure jitsi-jicofo Docker image is pulled
  community.docker.docker_image:
    name: "{{ jitsi_jicofo_container_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ jitsi_jicofo_container_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else jitsi_jicofo_container_image_force_pull }}"
  register: result
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: result is not failed

- name: Ensure jitsi-jicofo environment variables file created
  ansible.builtin.template:
    src: "{{ role_path }}/templates/jicofo/env.j2"
    dest: "{{ jitsi_jicofo_base_path }}/env"
    owner: "{{ jitsi_uid }}"
    group: "{{ jitsi_gid }}"
    mode: "0640"
  when: jitsi_enabled | bool

- name: Ensure jitsi-jicofo configuration files created
  ansible.builtin.template:
    src: "{{ role_path }}/templates/jicofo/{{ item }}.j2"
    dest: "{{ jitsi_jicofo_config_path }}/{{ item }}"
    owner: "{{ jitsi_uid }}"
    group: "{{ jitsi_gid }}"
    mode: "0644"
  with_items:
    - sip-communicator.properties
    - logging.properties

- name: Ensure jitsi-jicofo systemd service installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/jicofo/jicofo.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ jitsi_identifier }}-jicofo.service"
    mode: "0644"
