---

- name: Ensure jitsi-jvb path exists
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: "0777"
    owner: "{{ jitsi_uid }}"
    group: "{{ jitsi_gid }}"
  with_items:
    - {path: "{{ jitsi_jvb_base_path }}", when: true}
    - {path: "{{ jitsi_jvb_config_path }}", when: true}
  when: item.when | bool

- name: Ensure jitsi-jvb container image is pulled
  community.docker.docker_image:
    name: "{{ jitsi_jvb_container_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ jitsi_jvb_container_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else jitsi_jvb_container_image_force_pull }}"
  register: result
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: result is not failed

- name: Ensure jitsi-jvb configuration files created
  ansible.builtin.template:
    src: "{{ role_path }}/templates/jvb/{{ item }}.j2"
    dest: "{{ jitsi_jvb_config_path }}/{{ item }}"
    owner: "{{ jitsi_uid }}"
    group: "{{ jitsi_gid }}"
    mode: "0644"
  with_items:
    - custom-sip-communicator.properties
    - logging.properties

- name: Ensure jitsi-jvb support files installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/jvb/{{ item }}.j2"
    dest: "{{ jitsi_jvb_base_path }}/{{ item }}"
    owner: "{{ jitsi_uid }}"
    group: "{{ jitsi_gid }}"
    mode: "0640"
  with_items:
    - env
    - labels

- name: Ensure jitsi-jvb systemd service installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/jvb/jvb.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ jitsi_identifier }}-jvb.service"
    mode: "0644"
