---

galaxy_info:
  author: mash
  company: mash
  role_name: jitsi
  namespace: mash
  description: Jitsi
  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: Archlinux
      versions:
        - all
    - name: EL
      versions:
        - 7
  license: GPL-3.0-or-later
  min_ansible_version: '2.1'
