---

- name: Check existence of matrix-appservice-slack service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/matrix-appservice-slack.service"
  register: matrix_appservice_slack_service_stat

- when: matrix_appservice_slack_service_stat.stat.exists | bool
  block:
    - name: Ensure matrix-appservice-slack is stopped
      ansible.builtin.service:
        name: matrix-appservice-slack
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure matrix-appservice-slack.service doesn't exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/matrix-appservice-slack.service"
        state: absent
