---

- name: Remove old Docker apt repository, potentially lacking signed-by option
  ansible.builtin.file:
    path: "{{ matrix_playbook_migration_debian_signedby_migration_repository_path }}"
    state: absent
