---

# Tells whether this role had executed or not. Toggled to `true` during runtime.
matrix_nginx_proxy_role_executed: false

matrix_ssl_renewal_systemd_units_list:
  - name: matrix-ssl-lets-encrypt-certificates-renew.service
    applicable: "{{ matrix_ssl_retrieval_method == 'lets-encrypt' }}"
    enableable: false
    priority: 5000
    groups: ['matrix', 'nginx', 'ssl', 'reverse-proxies']
  - name: matrix-ssl-lets-encrypt-certificates-renew.timer
    applicable: "{{ matrix_ssl_retrieval_method == 'lets-encrypt' }}"
    enableable: true
    priority: 5000
    groups: ['matrix', 'nginx', 'ssl', 'reverse-proxies']
  - name: matrix-ssl-nginx-proxy-reload.service
    applicable: "{{ matrix_ssl_retrieval_method == 'lets-encrypt' and matrix_nginx_proxy_enabled | bool }}"
    enableable: false
    priority: 5000
    groups: ['matrix', 'nginx', 'ssl', 'reverse-proxies']
  - name: matrix-ssl-nginx-proxy-reload.timer
    applicable: "{{ matrix_ssl_retrieval_method == 'lets-encrypt' and matrix_nginx_proxy_enabled | bool }}"
    enableable: true
    priority: 5000
    groups: ['matrix', 'nginx', 'ssl', 'reverse-proxies']
