---

- name: Check existence of Redis service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ redis_identifier }}.service"
  register: redis_service_stat

- when: redis_service_stat.stat.exists | bool
  block:
    - name: Ensure Redis is stopped
      ansible.builtin.systemd:
        name: "{{ redis_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure Redis systemd service doesn't exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ redis_identifier }}.service"
        state: absent

- name: Check existence of Redis local data path
  ansible.builtin.stat:
    path: "{{ redis_data_path }}"
  register: redis_data_path_stat

# We just want to notify the user. Deleting data is too destructive.
- when: redis_data_path_stat.stat.exists | bool
  name: Notify if Redis local data remains
  ansible.builtin.set_fact:
    devture_playbook_runtime_messages_list: |
      {{
        devture_playbook_runtime_messages_list | default([])
        +
        [
          "Note: You are not using a local redis instance, but some old data remains from before in `{{ redis_data_path }}`. Feel free to delete it."
        ]
      }}

