---

- name: Ensure Traefik certs dumper paths exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0750"
    owner: "{{ devture_traefik_certs_dumper_uid }}"
    group: "{{ devture_traefik_certs_dumper_gid }}"
  with_items:
    - "{{ devture_traefik_certs_dumper_base_path }}"
    - "{{ devture_traefik_certs_dumper_bin_dir_path }}"

- name: Ensure Traefik certs dumper dumped certificates path exists
  ansible.builtin.file:
    path: "{{ devture_traefik_certs_dumper_dumped_certificates_dir_path }}"
    state: directory
    mode: "{{ devture_traefik_certs_dumper_dumped_certificates_dir_mode }}"
    owner: "{{ devture_traefik_certs_dumper_dumped_certificates_dir_owner }}"
    group: "{{ devture_traefik_certs_dumper_dumped_certificates_dir_group }}"

- name: Ensure Traefik certs dumper container image is pulled
  community.docker.docker_image:
    name: "{{ devture_traefik_certs_dumper_container_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"

- name: Ensure Traefik certs dumper scripts installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/bin/{{ item }}"
    dest: "{{ devture_traefik_certs_dumper_bin_dir_path }}/{{ item }}"
    owner: "{{ devture_traefik_certs_dumper_uid }}"
    group: "{{ devture_traefik_certs_dumper_gid }}"
    mode: 0750
  with_items:
    - wait-for-file.sh
    - wait-for-domain.sh
    - copy-certificates.sh
    - entrypoint.sh

- name: Ensure Traefik certs dumper systemd services installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/{{ item.src }}"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ item.dest }}"
    mode: 0644
  with_items:
    - src: devture-traefik-certs-dumper.service.j2
      dest: "{{ devture_traefik_certs_dumper_identifier }}.service"
    - src: devture-traefik-certs-dumper-wait-for-domain@.service.j2
      dest: "{{ devture_traefik_certs_dumper_identifier }}-wait-for-domain@.service"
