---

# Always validating the configuration, even if `matrix_nginx_proxy: false`.
# This role performs actions even if the role is disabled, so we need
# to ensure there's a valid configuration in any case.
- ansible.builtin.import_tasks: "{{ role_path }}/tasks/validate_config.yml"
  when: run_setup | bool
  tags:
    - setup-all
    - setup-nginx-proxy
    - install-all
    - install-nginx-proxy

- ansible.builtin.import_tasks: "{{ role_path }}/tasks/ssl/main.yml"
  when: run_setup | bool
  tags:
    - setup-all
    - setup-nginx-proxy
    - setup-ssl
    - install-all
    - install-nginx-proxy
    - install-ssl

- ansible.builtin.import_tasks: "{{ role_path }}/tasks/setup_nginx_proxy.yml"
  when: run_setup | bool
  tags:
    - setup-all
    - setup-nginx-proxy
    - install-all
    - install-nginx-proxy

- tags:
    - self-check
  block:
    - ansible.builtin.include_tasks: "{{ role_path }}/tasks/self_check_well_known.yml"

- name: Mark matrix-nginx-proxy role as executed
  tags:
    - always
  ansible.builtin.set_fact:
    matrix_nginx_proxy_role_executed: true
