---
- name: Ensure ipv6nat container image is pulled
  community.docker.docker_image:
    name: "{{ matrix_ipv6nat_container_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ matrix_ipv6nat_container_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else matrix_ipv6nat_container_image_force_pull }}"
  when: "not matrix_ipv6nat_container_image_self_build | bool"
  register: result
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: result is not failed

- name: Ensure matrix-ipv6nat.service installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/matrix-ipv6nat.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/matrix-ipv6nat.service"
    mode: 0644
