---

- tags:
    - setup-all
    - setup-mx-puppet-discord
    - install-all
    - install-mx-puppet-discord
  block:
    - when: matrix_mx_puppet_discord_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - when: matrix_mx_puppet_discord_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/setup_install.yml"

- tags:
    - setup-all
    - setup-mx-puppet-discord
  block:
    - when: not matrix_mx_puppet_discord_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/setup_uninstall.yml"
