---

- name: Fail if required mx-puppet-groupme settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item.name }}`).
  when: "item.when | bool and vars[item.name] == ''"
  with_items:
    - {'name': 'matrix_mx_puppet_groupme_appservice_token', when: true}
    - {'name': 'matrix_mx_puppet_groupme_homeserver_token', when: true}
    - {'name': 'matrix_mx_puppet_groupme_database_hostname', when: "{{ matrix_mx_puppet_groupme_database_engine == 'postgres' }}"}
